#include "DecisionEngine.h"
extern "C" {
    #include "model_compiled.h" // Treelite compiled model
}
#include "scaling_params.h" // Generated by train_model.py
#include <iostream>
#include <cmath>
#include <numeric>
#include <algorithm>
#include <string>

DecisionEngine::DecisionEngine(ExecutionInterface& execution, double risk_aversion, int window_size, bool use_ml) 
    : execution(execution), risk_aversion(risk_aversion), window_size(window_size), use_ml(use_ml) {}

double DecisionEngine::calculate_volatility() {
    if (price_history.size() < 2) return 0.0;
    
    double sum = std::accumulate(price_history.begin(), price_history.end(), 0.0);
    double mean = sum / price_history.size();
    
    double sq_sum = 0.0;
    for (double p : price_history) {
        sq_sum += (p - mean) * (p - mean);
    }
    
    return sq_sum / (price_history.size() - 1); // Sample variance
}

void DecisionEngine::on_event(const Features& features) {
    // Update Price History for Volatility
    if (features.midprice > 0) {
        price_history.push_back(features.midprice);
        if (price_history.size() > window_size) {
            price_history.pop_front();
        }
    }

    // Log for ML: timestamp,imbalance,spread,microprice,midprice,inventory,pnl
    double equity = execution.getTotalPnL(features.midprice); // Using PnL as proxy for equity tracking in logs
    
    // Calculate Volatility (Variance)
    double sigma_sq = calculate_volatility();
    
    // Avellaneda-Stoikov Logic
    // 1. Get Inventory (q)
    double q = execution.getInventory();
    
    // 2. Calculate Reservation Price (r)
    // r = s - q * gamma * sigma^2 + alpha (ML Signal)
    double s = features.midprice;
    
    double alpha_signal = 0.0;
    if (use_ml) {
        // ML Inference (Treelite)
        // Features: Imbalance, Spread, Arrival Rate, VPIN, Effective Spread, OFI
        // MUST MATCH python/train_model.py
        union Entry data[6];
        
        // Apply Scaling (Z-Score)
        data[0].fvalue = ((double)features.imbalance - MEAN_IMBALANCE) / SCALE_IMBALANCE;
        data[1].fvalue = ((double)features.spread - MEAN_SPREAD) / SCALE_SPREAD;
        data[2].fvalue = ((double)features.arrival_rate - MEAN_ARRIVAL_RATE) / SCALE_ARRIVAL_RATE;
        data[3].fvalue = ((double)features.vpin - MEAN_VPIN) / SCALE_VPIN;
        data[4].fvalue = ((double)features.effective_spread - MEAN_EFFECTIVE_SPREAD) / SCALE_EFFECTIVE_SPREAD;
        data[5].fvalue = ((double)features.ofi - MEAN_OFI) / SCALE_OFI;
        
        // predict returns the raw score (or leaf value sum)
        // For regression, this is the prediction.
        alpha_signal = predict(data, 0);
    } else {
        // Baseline: Pure Market Making (Alpha = 0)
        alpha_signal = 0.0;
    }
    
    last_alpha = alpha_signal;

    // Apply skew_factor to inventory term
    double r = s - q * risk_aversion * skew_factor * sigma_sq + alpha_signal;
    
    // 3. Calculate Quotes
    // Use fixed half_spread if set, otherwise dynamic
    double current_half_spread = (half_spread > 0) ? half_spread : (features.spread / 2.0);
    if (current_half_spread <= 0) current_half_spread = 0.5; // Fallback
    
    double bid_price = r - current_half_spread;
    double ask_price = r + current_half_spread;
    
    // Log State
    std::cout << "TICK," << features.timestamp << "," 
              << features.imbalance << "," 
              << features.spread << "," 
              << features.microprice << "," 
              << features.midprice << ","
              << q << ","
              << equity << ","
              << r << "," // Log Reservation Price
              << sigma_sq << "," // Log Volatility
              << alpha_signal << "," // Log Alpha Signal
              << features.arrival_rate << "," // Log Arrival Rate
              << features.vpin << "," // Log VPIN
              << features.effective_spread << "," // Log Effective Spread
              << features.ofi // Log OFI
              << std::endl; 

    // 4. Place Orders (Market Making)
    // Phase 6.1: Decision Dead-Zone & Signal Gating
    // Reduce noise trading by requiring sufficient model confidence before placing quotes.
    
    // Phase 7.4: Strategy Kill-Switch
    // Disable trading in High Volatility regimes where alpha is unstable.
    if (features.regime.find("HIGH_VOL") != std::string::npos) {
        // std::cout << "Kill-Switch Active: " << features.regime << std::endl;
        return;
    }

    // Rate Limiting
    if (features.timestamp - last_order_time < min_order_interval_ns) {
        return;
    }
    
    if (features.midprice <= 0.0) {
        return;
    }

    last_order_time = features.timestamp;

    constexpr double ALPHA_THRESHOLD = 0.0; // Changed from 0.5 to 0.0 for continuous quoting
    double quantity = order_size; // Use configured size
    double MAX_INVENTORY = max_inventory; // Use configured limit

    // Only trade if the signal is strong enough
    if (std::abs(alpha_signal) >= ALPHA_THRESHOLD) {
        // If alpha is positive (price expected to rise), we want to buy.
        // We place a BID.
        // For pure market making (alpha=0), we want to place BOTH?
        // The current logic splits:
        // if alpha > threshold -> BID
        // if alpha < -threshold -> ASK
        
        // If alpha is 0, we do nothing with the current logic!
        
        // We should probably place BOTH sides if alpha is small.
        // But let's just modify the logic to place both if alpha is near 0.
        
        bool place_bid = true;
        bool place_ask = true;
        
        if (alpha_signal > ALPHA_THRESHOLD) {
             place_ask = false; // Strong buy signal -> Don't sell? Or skew?
             // Standard AS places both, just skewed.
             // But this implementation seems to be "Directional".
        } else if (alpha_signal < -ALPHA_THRESHOLD) {
             place_bid = false;
        }
        
        // For this sanity check, let's force placing BOTH orders if alpha is 0.
        if (alpha_signal == 0.0) {
            place_bid = true;
            place_ask = true;
        } else {
             // Keep original logic for now?
             // Original:
             // if (alpha > 0.5) place BID
             // if (alpha < -0.5) place ASK
             
             // If I want to test AS, I should place both.
             place_bid = true;
             place_ask = true;
        }

        if (place_bid) {
            if (q < MAX_INVENTORY) {
                execution.placeOrder(true, bid_price, quantity, features.timestamp);
            }
        }
        if (place_ask) {
            if (q > -MAX_INVENTORY) {
                execution.placeOrder(false, ask_price, quantity, features.timestamp);
            }
        }
    }
}
